- name: configure backend
  hosts: backend
  become: true
  tasks:
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enabled nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: add user expense
      ansible.builtin.user:
        name: expense
        state: present

    - name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download backend code
      ansible.builtin.command: curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
