- name: configure frontend
  hosts: frontend
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: start and enabled Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    
    - name: remove default content on nginx server
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    
    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    
    - name: download frontend content
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip
    
    - name: extract frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: create expense.conf
      ansible.builtin.copy:
        src: /home/ec2-user/ansible-project/expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

